-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: detect-private-key
    -   id: double-quote-string-fixer
        language_version: python3
    -   id: end-of-file-fixer
    -   id: flake8
        language_version: python3
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.0.1
    hooks:
    -   id: remove-tabs
        language_version: python2.7
# TODO: Replace this with the actual repo
# (https://github.com/detailyang/pre-commit-shell)
# once it supports types and not just files ending in shell extensions
-   repo: local
    hooks:
    -   id: shell-lint
        name: Shell Syntax Check
        description: Check Shell Syntax on ALL staged files with user friendly messages and colors
        entry: shell-lint.sh
        language: script
        exclude: ^.deactivate.sh$
        types: [executable, shell]
